### ISSUE TITLE
Compatiblity with React 15.1.0

### ISSUE THREAD

**Issue by digitalpbk** [Fauntleroy/react-simple-dropdown#13]
Is this compatible with 15.1.0 ?
If yes, can you update the dependencies?

npm WARN react-simple-dropdown@1.1.0 requires a peer of react-dom@0.14.x || 15.0.x but none was installed.
npm WARN react-dom@15.1.0 requires a peer of react@^15.1.0 but none was installed.

**Comment by amertak** [comment]
I would suggest using peerDependency "^15.0.1" instead of "15.0.x" as we already have 15.1.0. Thanks ;)

**Comment by Fauntleroy** [comment]
Sorry for the delay. Updating and releasing now.
