### ISSUE TITLE
DropdownTrigger now requiring onClick prop is a breaking change in 1.1.3

### ISSUE THREAD

**Issue by Burneh** [Fauntleroy/react-simple-dropdown#16]
After upgrading we receive the following error

Warning: Failed propType: Required prop `onClick` was not specified in `DropdownTrigger`. Check the render method of `ProFilterStatus`

1.1.3 sets the prop for onClick in the DropdownTrigger.jsx file to be required. It was not previously required and we handled the events ourselves.

Sticking with 1.1.2 for now. Thanks!

**Comment by Fauntleroy** [comment]
I just released https://github.com/Fauntleroy/react-simple-dropdown/releases/tag/1.1.4 to resolve this issue. Looks like `cloneElement` and `propTypes` do not interact as I expected them to.
