### ISSUE TITLE
npm has incorrect props documentation

### ISSUE THREAD

**Issue by akeroyd** [Fauntleroy/react-simple-dropdown#23]
Hi, on the npm page for this package it says `show` is the prop to toggle the state of `DropdownComponent`, but in GitHub it is `active`.
I'm not sure why, as they both show the same version number.

**Comment by Fauntleroy** [comment]
Ah! That's probably because I updated the `readme.md` here on GitHub, but I haven't published to npm yet (since there have been no code changes). I'll have to see if there's some way to push the readme to npm, else I'll need to bump the version just for that change.

**Comment by Fauntleroy** [comment]
Fixed in `1.1.5`: https://www.npmjs.com/package/react-simple-dropdown
