### ISSUE TITLE
Remove href from dropdown trigger

### ISSUE THREAD

**Issue by selvagsz** [Fauntleroy/react-simple-dropdown#29]
What's the reason behind the href in the dropdown trigger? https://github.com/Fauntleroy/react-simple-dropdown/blob/6ac882a056afd2077e642b496b0664aec4b41c2b/src/components/DropdownTrigger.jsx#L25

I'm facing issue while migrating my angular app to react. NgRouter tries to navigate when clicking on the dropdown menu

**Comment by Fauntleroy** [comment]
That's a good question! I'm gonna look into it whether or not it truly does anything...

**Comment by selvagsz** [comment]
@Fauntleroy I'd forked & removed the href. Everything seemed to work fine though. If agreed upon, I can raise a PR to the upstream

**Comment by selvagsz** [comment]
@Fauntleroy Had a chance to look into this ?

**Comment by Fauntleroy** [comment]
https://github.com/Fauntleroy/react-simple-dropdown/releases/tag/2.0.0

**Comment by Fauntleroy** [comment]
The `href` should no longer appear in `2.0.0`. Just published to npm.

**Comment by selvagsz** [comment]
@Fauntleroy thanks
