### ISSUE TITLE
Add License Please

### ISSUE THREAD

**Issue by pmcavoy89** [Fauntleroy/react-simple-dropdown#32]
Could you add a license to this project please?

Thanks.

**Comment by Fauntleroy** [comment]
The license can be found here: https://github.com/Fauntleroy/react-simple-dropdown/blob/master/LICENSE

**Comment by pmcavoy89** [comment]
Can we add it to the `package.json` so that the warning goes away? Sorry about over looking the file though. 

Thanks for the quick response.
