### ISSUE TITLE
Stop propagation option

### ISSUE THREAD

**Issue by wavebeem** [Fauntleroy/react-simple-dropdown#34]
In https://github.com/tootsuite/mastodon/issues/1673#issuecomment-294278749 we're having issues because we can't stop propagation of menu events from this component.

Maybe there could be a top level prop like `disablePropagation={true}`?

**Comment by Fauntleroy** [comment]
Ideally I'd like to be able to make the `event` object available to you somehow so that you could `stopPropagation` on your own. I'll take a look at your use case soon and see about the best way to resolve this issue.

**Comment by wavebeem** [comment]
Cool, thanks!

**Comment by Fauntleroy** [comment]
@wavebeem it looks like your problem could potentially be solved by implementing prop passthrough, which I'm amenable to adding. Please tell me if the following works for you:

```jsx
class ExampleComponent extends Component {
  handleDropdownClick (event) {
    event.stopPropagation();
  }

  render () {
    return (
      <Dropdown onClick={this.handleDropdownClick}>
        <DropdownTrigger>Trigger</DropdownTrigger>
        <DropdownContent>Content</DropdownContent>
      </Dropdown>
    );
  }
}
```

**Comment by wavebeem** [comment]
I don't have a lot of background on the issue I mentioned unfortunately, so I'm asking back in that thread if this looks good. I'll circle back later and take a look myself if no one else chimes in. Thanks for taking a look!

**Comment by wavebeem** [comment]
The issue that caused me to come here and request this in the first place has stalled unfortunately. Is the change just adding the `event` parameter into the onClick handler? I'm sure that would be a solid fix for our issue, if we actually get around to it. Thanks for your time looking into this.

**Comment by Fauntleroy** [comment]
@wavebeem Actually, you should be able to do this *right now*:

```jsx
class ExampleComponent extends Component {
  handleDropdownClick (event) {
    event.stopPropagation();
  }

  render () {
    return (
      <Dropdown>
        <DropdownTrigger onClick={this.handleDropdownClick}>Trigger</DropdownTrigger>
        <DropdownContent>Content</DropdownContent>
      </Dropdown>
    );
  }
}
```

Props are currently passed wholesale to the `DropdownTrigger` and `DropdownContent` components, so you should be able to just specify an `onClick` handler for `DropdownTrigger` and `stopPropagation` there. I'm currently working on normalizing that behavior and making it work for the parent `Dropdown` component as well, but for your case this solution should work.

**Comment by wavebeem** [comment]
Fantastic! Thanks for your help.

**Comment by ShepelievD** [comment]
@Fauntleroy `event` is `undefined` on clicking
