### ISSUE TITLE
onShow is fired before the content is actually displayed.

### ISSUE THREAD

**Issue by omerman** [Fauntleroy/react-simple-dropdown#38]
I came across an issue
while trying to focus(using `element.focus()`) on the dropdown content when the `onShow` prop is fired.
The problem is that the dropdown content is still invisble when the `onShow` is fired.

I've taken a look at the code and noticed that currently the prop `onShow` is fired before the `setState({ active: true })` is applied(in `DropDown.js` => `show(){ ... }`).

I added a pull request (#37) regarding that matter, I'd be happy if you could take a look :-).

**Comment by Fauntleroy** [comment]
https://github.com/Fauntleroy/react-simple-dropdown/pull/37
