### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by jme783** [Fauntleroy/react-simple-dropdown#4]
`Unknown.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.`

This happens when I click on the dropdown trigger. Any thoughts?

**Comment by lukaszgrolik** [comment]
The same happens to me, React 0.14.3. Is this repo still maintained?

**Comment by Fauntleroy** [comment]
Sorry about this! I haven't cleaned this up for recent versions of React, but I'll get to it within the next day or so.

**Comment by Fauntleroy** [comment]
@jme783 @lukaszgrolik You should be able to use `1.0.0` from npm with no issues.

**Comment by lukaszgrolik** [comment]
Great, thanks!

**Comment by Fauntleroy** [comment]
@jme783 You will need to use `1.0.1`, as there is a critical problem with `1.0.0`.
