### ISSUE TITLE
How Can I change direction of dropdown menu?

### ISSUE THREAD

**Issue by willowTank** [Fauntleroy/react-simple-dropdown#47]
Hello I want to show top direction instead of down one.
Please help me.

**Comment by Fauntleroy** [comment]
@willowTank as of right now this module does not support any special positioning, so you'll need to do it manually. If you know the height of both your `DropdownContent` and `DropdownTrigger` it should be fairly trivial with CSS. If the size of either of these is dynamic, it could be more difficult.

I'm actually working on a feature which might make this easier, so stay tuned.

**Comment by willowTank** [comment]
Thanks for your time.
