### ISSUE TITLE
Cannot map inside dropdown menu

### ISSUE THREAD

**Issue by Arpit1294** [Fauntleroy/react-simple-dropdown#48]
So I have a status list of each seller that I want to map inside dropdown menu as list.
Now when I map it. It does not show any data but it works when the data is static.

here is my code 

`<Dropdown class="dropdown-menu--icons">
						<DropdownTrigger class={'btn btn-primary'}>
							ACTION
						<Icon class="icon inverse" icon="ICON_ANGLE_BOTTOM" />
						</DropdownTrigger>
							<DropdownMenu class="dropdown-menu-right">
								{this.renderDropdownAction(this.props.seller.sellerRegistrationStatusList)}
							</DropdownMenu>
					</Dropdown>`

`renderDropdownAction(sellerList) {
		if(sellerList){
			console.log(sellerList);
			console.log("ssssssssssssssssssssssssss");
			return sellerList.map((statusObj)=>{
			return ( 
				<li>
						<a class="menu-item" >
							{statusObj.id}
						</a>
				</li>
			);
			})
		}else{
			return (
				<li>
					<a class="menu-item" >
						Not working
					</a>
			</li>
		);
		}		
  }`

**Comment by Fauntleroy** [comment]
What is `DropdownMenu`? Do you have a complete example of this code, including the imports?

**Comment by Arpit1294** [comment]
It was my fault. Wrote some bad code. Thanks for replying.
