### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by tomellwood** [Fauntleroy/react-simple-dropdown#51]
react-simple-dropdown@3.2.0 requires a peer of react@0.14.x || 15.x but none was installed.
react-simple-dropdown@3.2.0 requires a peer of react-dom@0.14.x || 15.x but none was installed.

**Comment by sastoveza** [comment]
Wondering the same thing? Any updates?

**Comment by iamsoorena** [comment]
I recently updated my react app and suddenly my dropdowns stopped working, when will this problem resolve?

**Comment by Fauntleroy** [comment]
This issue should be resolved with version 3.2.1
