### ISSUE TITLE
onClick inside dropdown not working

### ISSUE THREAD

**Issue by LyhjeHylje** [Fauntleroy/react-simple-dropdown#55]
For some reason onClicks inside my dropdown are not firing, even this simplest possible example is not working and I cannot figure out why

```javascript
                        <Dropdown>
                            <DropdownTrigger>Username</DropdownTrigger>
                            <DropdownContent>
                                <ul>
                                    <li>
                                        <a
                                            onClick={() => {
                                                console.log("boo");
                                            }}
                                            href="javascript:void(0);"
                                        >
                                            Sign out
                                        </a>
                                    </li>
                                </ul>
                            </DropdownContent>
                        </Dropdown>
```

**Comment by Fauntleroy** [comment]
I can't replicate this issue locally using the code supplied. Which version of the component are you using?

**Comment by LyhjeHylje** [comment]
I am using the latest version, but it seems that the problems were somewhere else: I left the dropdown code in place and started working on the rest of my site and at some point noticed that the onclick works. 
Probably some other element was covering dropdown's a-tag or somehow interfering with it.
Sorry about the false alarm.
