### ISSUE TITLE
v1.0.0 - Webpack: Module not found: Error: Cannot resolve module 'react-simple-dropdown'

### ISSUE THREAD

**Issue by lukaszgrolik** [Fauntleroy/react-simple-dropdown#6]
I even tried to remove `node_modules/` and reinstall all packages, still the same. When I switch back to v0.1.1 it works again.

**Comment by Fauntleroy** [comment]
Can you provide any more error information? What method were you using to include the module?

**Comment by lukaszgrolik** [comment]
```js
import Dropdown from 'react-simple-dropdown';
```
It works with v0.1.1

**Comment by Fauntleroy** [comment]
Are you installing through `npm`?

**Comment by lukaszgrolik** [comment]
Yes

**Comment by Fauntleroy** [comment]
`1.0.1` should work. There was a configuration error stemming from my switch to compiled JS which should be resolved now.

https://github.com/Fauntleroy/react-simple-dropdown/commit/f91217c9b6cff31f954bb964b5d326797ac0d103
