### ISSUE TITLE
Webpack can't resolve 'react-simple-dropdown' after upgrade from 3.2.0 to 3.2.1

### ISSUE THREAD

**Issue by mray-infor** [Fauntleroy/react-simple-dropdown#60]
Hello there,

We have a project that we are building with webpack, using babel-loader and awesome-typescript-loader. All node dependencies, including react-simple-dropdown, are installed with `npm install`. After the 3.2.1 update, `npm run serve` began failing with the following error message from webpack:

```
ERROR in ./app/components/user/User.tsx
Module not found: Error: Can't resolve 'react-simple-dropdown' in '/[REDACTED]/ui/app/components/user'
 @ ./app/components/user/User.tsx 13:27-59
 @ ./app/components/pages/masterPage/MasterPage.tsx
 @ ./app/components/App.tsx
 @ ./app/index.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8086 ./app/index.ts
```

I checked, and npm did download the `react-simple-dropdown` package to the usual location. Downgrading to 3.2.0 fixes the problem. Do you know what might cause this?

**Comment by Fauntleroy** [comment]
I'm not sure why that would be happening, since the only change between `3.2.0` and `3.2.1` is a modification of the `peerDependencies`: https://github.com/Fauntleroy/react-simple-dropdown/commit/8f01a727028475defbc92af2ee9186251d8c9927

**Comment by fr33l** [comment]
We are affected by this as well, but it's rather  intermittent, might be related to node version? For us it's failing with  node v6.11.2 , but builds with node v.10.7.0

**Comment by smitch88** [comment]
Also running into this issue with webpack builds. Failing all our circleci builds because of it. @fr33l Did you narrow it down to a potential node versioning issue? We run node `v9.11.1` but also cannot upgrade to node 10 if that does successfully build as expected

**Comment by eugeneford** [comment]
@smitch88, in our case (@fr33l) we are not facing this issue with node@10, but are facing with node@6. So yes, node version can be the potential issue, but we did test it yet

**Comment by smitch88** [comment]
@Fauntleroy Not sure if it makes a difference because Im not as well versed with peer deps aspect but another repo which recently did the same thing, `react-icons`, has their versions with a semver pattern e.g, `14.x.x` instead of just `14.x`

Reference:
https://github.com/react-icons/react-icons/pull/117/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R59

**Comment by mray-infor** [comment]
@fr33l We are using node v6.9.2, so that could be it.

Inspecting the difference between 3.2.0 and 3.2.1 on my own machine, there is some kind of massive change in the `lib` subdirectory:

![screenshot from 2018-08-03 10-10-07](https://user-images.githubusercontent.com/36543569/43647536-e12531c8-9705-11e8-848e-e80986aad933.png)

**Comment by Fauntleroy** [comment]
![cg2wtu2vhtoguh3bfdnetjap2dyuxuhq62wj3eihca0](https://user-images.githubusercontent.com/507047/43649670-9bd553d6-96f2-11e8-8b66-a60b569d6f95.jpg)


This issue has been resolved by https://github.com/Fauntleroy/react-simple-dropdown/commit/7395f5d75e34b8764346839807d0d4120e4d646b. **Please install version 3.2.2**.

As for what actually went wrong: I had been switching between the `master` branch and another feature branch (where the filenames have been changed to eliminate capital letter issues). This meant that there was stale duplicate code which could cause path resolution issues in the `/lib` directory when I published the module. The commit above ensures that the `/lib` directory is clean before the module is built and published.

Thanks to @mray-infor for reporting the issue and posting the very instructive screenshot of the directory diff.

**Comment by mray-infor** [comment]
Looks good, thanks!
