### ISSUE TITLE
Module not found error - Facing issue in the file name dropdown.js

### ISSUE THREAD

**Issue by alex6633** [Fauntleroy/react-simple-dropdown#61]
Hi Team,
I was using the version react-simple-dropdown version 3.2.0 all these and it worked perfectly fine for me without any issues. But somehow when I am doing Yarn install I am getting the below error.

**Module not found: `C:\myFolder\myProject\myWork\myApp\node_modules\react-simple-dropdown\lib\components\Dropdown.js` does not match the corresponding path on disk `dropdown.js`.** 

When I tried to dig deep I noticed that the file name is dropdown.js where in the class Name is Dropdown.js. Hence I changed the filename to Dropdown.js from dropdown.js and it works fine now. 
But it is actually not recommended to change the auto generated files so any other solution here ?
Could you please help me on this?

Thanks in advance,
Alex

**Comment by Fauntleroy** [comment]
@alex6633 Are you using version `3.2.1`? There was an issue with the `/lib` directory that the recently released `3.2.2` solves.

**Comment by alex6633** [comment]
Hi @Fauntleroy ,

No I am using version 3.2.2 .

**Comment by Fauntleroy** [comment]
Alright, it seems like this is the case issue my other feature branch solved. I'll quickly fix this issue and make my second release of the morning 😬

**Comment by alex6633** [comment]
Hi @Fauntleroy ,
Thank you so much for your quick response. :)
I will check once again and update you shortly on this.

Regards,
Alex

**Comment by takempf** [comment]
@alex6633 3.2.3 is now released. This should resolve the issue.

**Comment by alex6633** [comment]
Hi @Fauntleroy ,
Yayyy!!! 🥇 
It works now
Thank you so much.


Regards,
Alex
