### ISSUE TITLE
Dropdown doesn't hide on single page web apps

### ISSUE THREAD

**Issue by mleonard87** [Fauntleroy/react-simple-dropdown#9]
I'm using this drop down on a single page web app with the Dropdown in a global header. In the Dropdown I have links for navigation change the URL. Its a single page web app so its just changing route and the page doesn't reload. As such, after clicking a link and having the page change the Dropdown is still in its active state which is not desirable. This is because the component never umounts/mounts.

I've done some experimentation and put the modified `_onWindowClick` as follows:
```javascript
_onWindowClick: function( event ){
    const dropdown_element = findDOMNode( this );
    if( event.target !== dropdown_element && !dropdown_element.contains( event.target ) && this.isActive() ){
      this.hide();
    }

    if (dropdown_element.contains( event.target ) && event.target.tagName === 'A' && !event.target.href.endsWith('#dropdown-trigger')) {
      this.hide();
    }
  }
```

The additional last `if` is says that:
* If the `event.target` is contained with the Dropdown; and 
* its an A tag;
* and that A tag does not have an href which ends with the trigger link itself;
* **then hide the menu**.

This doesn't seem like the most elegant solution but it works.

I'm happy to submit a pull request with this or with any other suggestions you might have.

**Comment by Fauntleroy** [comment]
I've had this issue before in the distant past, and I seem to recall basically turning this into a controlled component and using the `show` property to manually hide/show the dropdown when appropriate.

Your solution would work for this specific use case, but I'd like to take some time to think of other situations which might call for this functionality.

**Comment by csterritt** [comment]
For whatever it's worth, I just set a "ref" on the `DropDown`, and then in my click-handler code for the `DropDownContent` I put:

```js
    const drop_down = this.refs.drop_down_obj;
    drop_down.hide();
```

**Comment by tyrsius** [comment]
@Fauntleroy even just putting a property on the Dropdown like `closeOnClick` would be a big improvement. For Certain kinds of dropdowns *any* click should close it, inside or out.

**Comment by Fauntleroy** [comment]
I'll look into an update which should allow something like this:

```js
const MyDropdown = React.createClass({
  render () {
    return (<Dropdown ref="dropdown">
      <DropdownTrigger>Trigger</DropdownTrigger>
      <DropdownContent onClick={()=>{this.refs.dropdown.hide()}>
        Content
      </DropdownContent>
    </Dropdown>);
  }
});
```

**Comment by Fauntleroy** [comment]
@tyrsius I just published https://github.com/Fauntleroy/react-simple-dropdown/releases/tag/1.1.3, which will allow you to use the code above to hide the dropdown anytime anything within `DropdownContent` is clicked.

Since I do not plan on introducing a more elaborate way of doing this in the forseeable future, I'll close this issue for now.

**Comment by LeonardoGentile** [comment]
If anybody is still interested in this, I've solved it in another way. 
In the Dropdown render method we already [stick callback on trigger element ](https://github.com/Fauntleroy/react-simple-dropdown/blob/master/src/components/Dropdown.jsx#L84) so after that I stick another callback but this time on the DropdownContent element so that it will handle any event from the underlying elements before the event bubbles up and reach the Dropdown (parent).

```
if (child.type === DropdownContent) {
  const originalOnClick = child.props.onClick;
  child = cloneElement(child, {
    ref: 'content',
    onClick: (event) => {
      this.hide();
      if (originalOnClick) {
        originalOnClick.apply(child, arguments);
      }
    }
  });
}
```

**Comment by mjoyce91** [comment]
I was getting a `react/no-string-refs` lint error, but took a look at [this documentation about Refs and the DOM](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element) and was able to get something working:

```jsx
export class AccountDropdown extends Component {
constructor(props) {
    super(props);
    this.hideDropdown = this.hideDropdown.bind(this);
  }
hideDropdown() {
    // Explicitly hide the dropdown using the built-in hide() function from react-simple-dropdown
    this.dropdown.hide();
  }
render() {
    return (
      <Dropdown className="account-dropdown" ref={(dropdown) => { this.dropdown = dropdown; }} >
        <DropdownTrigger href="/#">
        </DropdownTrigger>
        <DropdownContent>
          <div className="account-dropdown--identity account-dropdown--segment">
            <Link to="/profile" onClick={this.hideDropdown}>Profile</Link>
          </div>
        </DropdownContent>
      </Dropdown>
    );
  }
}
```
